---
name: Devel-SimpleTrace
version: 0.07
author:
  - 'Sébastien Aperghis-Tramoni <sebastien@aperghis.net>'
abstract: See where you code warns and dies using stack traces
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::Dumper: 0
build_requires:
  Test: 0
  Test::More: 0
provides:
  Devel::SimpleTrace:
    file: lib/Devel/SimpleTrace.pm
    version: 0.07
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
