--- #YAML:1.0
name: Devel-SimpleTrace
version: 0.04
author:
  - |-
    Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: |-
  See where you code warns and dies using stack traces
license: perl
provides:
  Devel::SimpleTrace:
    file: lib/Devel/SimpleTrace.pm
    version: 0.04
generated_by: Module::Build version 0.2607
