---
name: Devel-SimpleTrace
version: 0.06
author:
  - Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: See where you code warns and dies using stack traces
license: perl
requires:
  Data::Dumper: 0
provides:
  Devel::SimpleTrace:
    file: lib/Devel/SimpleTrace.pm
    version: 0.06
generated_by: Module::Build version 0.2611
